import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import Share from 'react-native-share';

const A4_WIDTH = 595.28;
const A4_HEIGHT = 841.89;
const PAGE_MARGIN = 32;
const FOOTER_HEIGHT = 24;

export type EcgReportShareMetadata = {
  fileStem: string;
  title: string;
  subject: string;
};

export async function createEcgReportPdfBase64(
  pngBase64: string,
  title: string,
): Promise<string> {
  const document = await PDFDocument.create();
  document.setTitle(title);
  document.setCreator('Healthsoft');
  document.setProducer('Healthsoft mobile app');
  document.setCreationDate(new Date());

  const page = document.addPage([A4_WIDTH, A4_HEIGHT]);
  const image = await document.embedPng(pngBase64);
  const availableWidth = A4_WIDTH - PAGE_MARGIN * 2;
  const availableHeight =
    A4_HEIGHT - PAGE_MARGIN * 2 - FOOTER_HEIGHT;
  const scale = Math.min(
    availableWidth / image.width,
    availableHeight / image.height,
  );
  const imageWidth = image.width * scale;
  const imageHeight = image.height * scale;
  const imageX = (A4_WIDTH - imageWidth) / 2;
  const imageY = A4_HEIGHT - PAGE_MARGIN - imageHeight;

  page.drawImage(image, {
    x: imageX,
    y: imageY,
    width: imageWidth,
    height: imageHeight,
  });

  const font = await document.embedFont(StandardFonts.Helvetica);
  page.drawText('Generated by Healthsoft - Device waveform, not a diagnosis', {
    x: PAGE_MARGIN,
    y: 18,
    size: 8,
    font,
    color: rgb(0.45, 0.42, 0.4),
  });

  return document.saveAsBase64({ dataUri: false });
}

export async function shareEcgReportPng(
  pngBase64: string,
  metadata: EcgReportShareMetadata,
): Promise<void> {
  await Share.open({
    title: metadata.title,
    subject: metadata.subject,
    filename: `${metadata.fileStem}.png`,
    type: 'image/png',
    url: `data:image/png;base64,${pngBase64}`,
    failOnCancel: false,
    useInternalStorage: true,
  });
}

export async function shareEcgReportPdf(
  pngBase64: string,
  metadata: EcgReportShareMetadata,
): Promise<void> {
  const pdfBase64 = await createEcgReportPdfBase64(
    pngBase64,
    metadata.title,
  );
  await Share.open({
    title: metadata.title,
    subject: metadata.subject,
    filename: `${metadata.fileStem}.pdf`,
    type: 'application/pdf',
    url: `data:application/pdf;base64,${pdfBase64}`,
    failOnCancel: false,
    useInternalStorage: true,
  });
}
